spring:
  application:
    name: micro-panel-backend

server:
  port: 8080

panel:
  upstream:
    # Base URL de l'API qui expose les scènes (inclure le préfixe /api si nécessaire)
    base-url: http://10.41.40.130:1234/
